### ISSUE TITLE
openapi: golang: impossible to disable dax or set cache size to zero

### ISSUE THREAD

**Issue by devimc** [cloud-hypervisor/cloud-hypervisor#1961]
The following chuck of code is the definition of `FsConfig` in  [cloud-hypervisor.yaml][1]

```yaml
    FsConfig:
      required:
      - tag
      - socket
      type: object
      properties:
        tag:
          type: string
        socket:
          type: string
        num_queues:
          type: integer
          default: 1
        queue_size:
          type: integer
          default: 1024
        dax:
          type: boolean
          default: true
        cache_size:
          type: integer
          format: int64
          default: 8589934592
        id:
          type: string
```

In Kata Containers we use the [openapi-generator container][2] to generate the client code in Golang, the following chuck of code is how openapi-generator generates the structure type for `FsConfig`

```go
type FsConfig struct {
	Tag string `json:"tag"`
	Socket string `json:"socket"`
	NumQueues int32 `json:"num_queues,omitempty"`
	QueueSize int32 `json:"queue_size,omitempty"`
	Dax bool `json:"dax,omitempty"`
	CacheSize int64 `json:"cache_size,omitempty"`
	Id string `json:"id,omitempty"`
}
```

notice that the json tags for `Dax` and `CacheSize` contains the option `omitempty`, so when these fields (Dax and CacheSize) will be omitted from the final json (final client request) when they are empty (false and 0 respectively), **making impossible to disable dax or set cache size to zero**
This is a know limitation of openapi-generator, as is described here https://github.com/OpenAPITools/openapi-generator/issues/7511 

## Solutions:

**Solution 1**:

Mark `dax`  and `cache_size` as required, `omitempty` option is removed from the json tag

```yaml
    FsConfig:
      required:
      - tag
      - socket
      - dax
      - cache_size
```

**Solutions 2:**

Make `dax`  and `cache_size` pointers, `omitempty` **is not** removed from the json tag, but pointer to `false` and `0` are not omitted

```yaml
    FsConfig:
      required:
      - tag
      - socket
      type: object
      properties:
        tag:
          type: string
        socket:
          type: string
        num_queues:
          type: integer
          default: 1
        queue_size:
          type: integer
          default: 1024
        dax:
          type: boolean
          default: true
          nullable: true
        cache_size:
          type: integer
          format: int64
          default: 8589934592
          nullable: true
        id:
          type: string
```
-----

@likebreath @rbradford what do you think? any other idea to deal with this limitation?

Thanks

[1]: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/api/openapi/cloud-hypervisor.yaml
[2]: https://hub.docker.com/r/openapitools/openapi-generator-cli/
