### ISSUE TITLE
setup bridge network: create bridge: file exists

### ISSUE THREAD

**Issue by laoyang103** [cloud-hypervisor/cloud-hypervisor#6435]
**Describe the bug**
create pod vm on k8s error
```bash
[root@master ~]# kubectl -n ns-jx00000003 logs pod/jx00000003-ops-81 
Defaulted container "cloud-hypervisor" out of: cloud-hypervisor, init-kernel (init), init-volume-ubuntu (init), init-volume-cloud-init (init)
2024/05/02 03:23:57 Failed to build VM config: setup bridge network: create bridge: file exists
```
**k8s yaml**
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: ns-jx00000003
  name: jx00000003-ops-81
  annotations:
    ovn.kubernetes.io/logical_switch: subnet-jx00000003
    ovn.kubernetes.io/ip_address: 10.10.10.81
spec:
  nodeSelector:
    kubernetes.io/hostname: ubuntu-22-04
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.16.255.254
      - 114.114.114.114
  initContainers:
  - args:
    - /mnt/virtink-kernel/vmlinux
    image: registry.jxit.net.cn:5000/qdcloud/virtink-kernel:5.18.8
    imagePullPolicy: Always
    name: init-kernel
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/virtink-kernel
      name: virtink-kernel
  - args:
    - /mnt/ubuntu/rootfs.raw
    - "42949672960"
    image: registry.jxit.net.cn:5000/qdcloud/init-rootfs-ubuntu:no-over
    imagePullPolicy: Always
    name: init-volume-ubuntu
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/ubuntu
      name: ubuntu
  - args:
    - cloud-init
    - aW5zdGFuY2UtaWQ6IDVkZTlkNTNlLTAyMTYtNGI1MC04NmVhLWY2M2QzZmFiNzMyYwpsb2NhbC1ob3N0bmFtZTogdWJ1bnR1LWNvbnRhaW5lci1yb290ZnM=
    - I2Nsb3VkLWNvbmZpZwpzc2hfcHdhdXRoOiBUcnVlCmNocGFzc3dkOgogIGxpc3Q6IHwKICAgICByb290OjEyMwogICAgIHVidW50dToxMjMKICBleHBpcmU6IEZhbHNlCmJvb3RjbWQ6CiAgLSBlY2hvIFBlcm1pdFJvb3RMb2dpbiB5ZXMgPj4gL2V0Yy9zc2gvc3NoZF9jb25maWc=
    - ""
    - /mnt/cloud-init/cloud-init.iso
    command:
    - virt-init-volume
    image: smartxworks/virt-prerunner:v0.13.0@sha256:44311e42fb3fb4823a755d487c728535ba928efa8e449a3b3b5b8617360bacf6
    imagePullPolicy: IfNotPresent
    name: init-volume-cloud-init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/cloud-init
      name: cloud-init
  containers:
  - args:
    - --vm-data
    - eyJraW5kIjoiVmlydHVhbE1hY2hpbmUiLCJhcGlWZXJzaW9uIjoidmlydC52aXJ0aW5rLnNtYXJ0eC5jb20vdjFhbHBoYTEiLCJtZXRhZGF0YSI6eyJuYW1lIjoidWJ1bnR1LWNvbnRhaW5lci1yb290ZnMiLCJuYW1lc3BhY2UiOiJkZWZhdWx0IiwidWlkIjoiNWRlOWQ1M2UtMDIxNi00YjUwLTg2ZWEtZjYzZDNmYWI3MzJjIiwicmVzb3VyY2VWZXJzaW9uIjoiMjU2MTEiLCJnZW5lcmF0aW9uIjoxLCJjcmVhdGlvblRpbWVzdGFtcCI6IjIwMjQtMDQtMjBUMDY6MDQ6NDFaIiwiYW5ub3RhdGlvbnMiOnsia3ViZWN0bC5rdWJlcm5ldGVzLmlvL2xhc3QtYXBwbGllZC1jb25maWd1cmF0aW9uIjoie1wiYXBpVmVyc2lvblwiOlwidmlydC52aXJ0aW5rLnNtYXJ0eC5jb20vdjFhbHBoYTFcIixcImtpbmRcIjpcIlZpcnR1YWxNYWNoaW5lXCIsXCJtZXRhZGF0YVwiOntcImFubm90YXRpb25zXCI6e30sXCJuYW1lXCI6XCJ1YnVudHUtY29udGFpbmVyLXJvb3Rmc1wiLFwibmFtZXNwYWNlXCI6XCJkZWZhdWx0XCJ9LFwic3BlY1wiOntcImluc3RhbmNlXCI6e1wiZGlza3NcIjpbe1wibmFtZVwiOlwidWJ1bnR1XCJ9LHtcIm5hbWVcIjpcImNsb3VkLWluaXRcIn1dLFwiaW50ZXJmYWNlc1wiOlt7XCJuYW1lXCI6XCJwb2RcIn1dLFwia2VybmVsXCI6e1wiY21kbGluZVwiOlwiY29uc29sZT10dHlTMCByb290PS9kZXYvdmRhIHJ3XCIsXCJpbWFnZVwiOlwic21hcnR4d29ya3MvdmlydGluay1rZXJuZWwtNS4xNS4xMlwifSxcIm1lbW9yeVwiOntcInNpemVcIjpcIjFHaVwifX0sXCJuZXR3b3Jrc1wiOlt7XCJuYW1lXCI6XCJwb2RcIixcInBvZFwiOnt9fV0sXCJ2b2x1bWVzXCI6W3tcImNvbnRhaW5lclJvb3Rmc1wiOntcImltYWdlXCI6XCJzbWFydHh3b3Jrcy92aXJ0aW5rLWNvbnRhaW5lci1yb290ZnMtdWJ1bnR1XCIsXCJzaXplXCI6XCI0R2lcIn0sXCJuYW1lXCI6XCJ1YnVudHVcIn0se1wiY2xvdWRJbml0XCI6e1widXNlckRhdGFcIjpcIiNjbG91ZC1jb25maWdcXG5wYXNzd29yZDogcGFzc3dvcmRcXG5jaHBhc3N3ZDogeyBleHBpcmU6IEZhbHNlIH1cXG5zc2hfcHdhdXRoOiBUcnVlXCJ9LFwibmFtZVwiOlwiY2xvdWQtaW5pdFwifV19fVxuIn0sIm1hbmFnZWRGaWVsZHMiOlt7Im1hbmFnZXIiOiJrdWJlY3RsLWNsaWVudC1zaWRlLWFwcGx5Iiwib3BlcmF0aW9uIjoiVXBkYXRlIiwiYXBpVmVyc2lvbiI6InZpcnQudmlydGluay5zbWFydHguY29tL3YxYWxwaGExIiwidGltZSI6IjIwMjQtMDQtMjBUMDY6MDQ6NDFaIiwiZmllbGRzVHlwZSI6IkZpZWxkc1YxIiwiZmllbGRzVjEiOnsiZjptZXRhZGF0YSI6eyJmOmFubm90YXRpb25zIjp7Ii4iOnt9LCJmOmt1YmVjdGwua3ViZXJuZXRlcy5pby9sYXN0LWFwcGxpZWQtY29uZmlndXJhdGlvbiI6e319fSwiZjpzcGVjIjp7Ii4iOnt9LCJmOmluc3RhbmNlIjp7Ii4iOnt9LCJmOmRpc2tzIjp7fSwiZjppbnRlcmZhY2VzIjp7fSwiZjprZXJuZWwiOnsiLiI6e30sImY6Y21kbGluZSI6e30sImY6aW1hZ2UiOnt9fSwiZjptZW1vcnkiOnsiLiI6e30sImY6c2l6ZSI6e319fSwiZjpuZXR3b3JrcyI6e30sImY6dm9sdW1lcyI6e319fX0seyJtYW5hZ2VyIjoidmlydC1jb250cm9sbGVyIiwib3BlcmF0aW9uIjoiVXBkYXRlIiwiYXBpVmVyc2lvbiI6InZpcnQudmlydGluay5zbWFydHguY29tL3YxYWxwaGExIiwidGltZSI6IjIwMjQtMDQtMjBUMDY6MDQ6NDFaIiwiZmllbGRzVHlwZSI6IkZpZWxkc1YxIiwiZmllbGRzVjEiOnsiZjpzdGF0dXMiOnsiZjpwaGFzZSI6e30sImY6dm1Qb2ROYW1lIjp7fX19LCJzdWJyZXNvdXJjZSI6InN0YXR1cyJ9LHsibWFuYWdlciI6InZpcnQtZGFlbW9uIiwib3BlcmF0aW9uIjoiVXBkYXRlIiwiYXBpVmVyc2lvbiI6InZpcnQudmlydGluay5zbWFydHguY29tL3YxYWxwaGExIiwidGltZSI6IjIwMjQtMDQtMjBUMDY6MDQ6NDFaIiwiZmllbGRzVHlwZSI6IkZpZWxkc1YxIiwiZmllbGRzVjEiOnsiZjpzdGF0dXMiOnt9fSwic3VicmVzb3VyY2UiOiJzdGF0dXMifV19LCJzcGVjIjp7InJlc291cmNlcyI6e30sInJ1blBvbGljeSI6Ik9uY2UiLCJpbnN0YW5jZSI6eyJjcHUiOnsic29ja2V0cyI6MiwiY29yZXNQZXJTb2NrZXQiOjJ9LCJtZW1vcnkiOnsic2l6ZSI6IjhHaSJ9LCJrZXJuZWwiOnsiaW1hZ2UiOiJzbWFydHh3b3Jrcy92aXJ0aW5rLWtlcm5lbC01LjE1LjEyIiwiY21kbGluZSI6ImNvbnNvbGU9dHR5UzAgcm9vdD0vZGV2L3ZkYSBydyJ9LCJkaXNrcyI6W3sibmFtZSI6InVidW50dSJ9LHsibmFtZSI6ImNsb3VkLWluaXQifV0sImludGVyZmFjZXMiOlt7Im5hbWUiOiJwb2QiLCJtYWMiOiI1Mjo1NDowMDplMjoxNjplYSIsImJyaWRnZSI6e319XX0sInZvbHVtZXMiOlt7Im5hbWUiOiJ1YnVudHUiLCJjb250YWluZXJSb290ZnMiOnsiaW1hZ2UiOiJzbWFydHh3b3Jrcy92aXJ0aW5rLWNvbnRhaW5lci1yb290ZnMtdWJ1bnR1Iiwic2l6ZSI6IjQwR2kifX0seyJuYW1lIjoiY2xvdWQtaW5pdCIsImNsb3VkSW5pdCI6eyJ1c2VyRGF0YSI6IiNjbG91ZC1jb25maWdcbnBhc3N3b3JkOiBwYXNzd29yZFxuY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9XG5zc2hfcHdhdXRoOiBUcnVlIn19XSwibmV0d29ya3MiOlt7Im5hbWUiOiJwb2QiLCJwb2QiOnt9fV19LCJzdGF0dXMiOnsicGhhc2UiOiJTY2hlZHVsaW5nIiwidm1Qb2ROYW1lIjoidm0tdWJ1bnR1LWNvbnRhaW5lci1yb290ZnMtcWdyZHgifX0=
    image: smartxworks/virt-prerunner:v0.13.0@sha256:44311e42fb3fb4823a755d487c728535ba928efa8e449a3b3b5b8617360bacf6
    imagePullPolicy: IfNotPresent
    name: cloud-hypervisor
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
        - NET_ADMIN
        - SYS_RESOURCE
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/kvm
      name: devkvm
    - mountPath: /dev/net/tun
      name: devtun
    - mountPath: /var/run/virtink
      name: virtink
    - mountPath: /mnt/virtink-kernel
      name: virtink-kernel
    - mountPath: /mnt/ubuntu
      name: ubuntu
    - mountPath: /mnt/cloud-init
      name: cloud-init
  volumes:
  - name: devkvm
    hostPath:
      path: /dev/kvm
  - name: devtun
    hostPath:
      path: /dev/net/tun
  - emptyDir: {}
    name: virtink
  - emptyDir: {}
    name: virtink-kernel
  - name: ubuntu
    persistentVolumeClaim:
      claimName: jx00000003-ops-81-pvc
  - emptyDir: {}
    name: cloud-init
```

**Version**

```bash
root@ubuntu-22-04:~# cloud-hypervisor --version
cloud-hypervisor v38.0.0
```
**Command**

```bash
cloud-hypervisor --api-socket /var/run/virtink/ch.sock --console pty --serial tty --kernel /mnt/virtink-kernel/vmlinux --cmdline console=ttyS0 root=/dev/vda rw --cpus boot=4,topology=1:2:1:2,affinity= --memory size=8589934592 --disk id=ubuntu,path=/mnt/ubuntu/rootfs.raw,direct=on id=cloud-init,path=/mnt/cloud-init/cloud-init.iso,direct=on --net id=pod,mac=00:00:00:04:49:3b,tap=tap-eth0,mtu=1400
```

**VM configuration**
```json
{
	"kind": "VirtualMachine",
	"apiVersion": "virt.virtink.smartx.com/v1alpha1",
	"metadata": {
		"name": "ubuntu-container-rootfs",
		"namespace": "default",
		"uid": "5de9d53e-0216-4b50-86ea-f63d3fab732c",
		"resourceVersion": "25611",
		"generation": 1,
		"creationTimestamp": "2024-04-20T06:04:41Z",
		"annotations": {
			"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"virt.virtink.smartx.com/v1alpha1\",\"kind\":\"VirtualMachine\",\"metadata\":{\"annotations\":{},\"name\":\"ubuntu-container-rootfs\",\"namespace\":\"default\"},\"spec\":{\"instance\":{\"disks\":[{\"name\":\"ubuntu\"},{\"name\":\"cloud-init\"}],\"interfaces\":[{\"name\":\"pod\"}],\"kernel\":{\"cmdline\":\"console=ttyS0 root=/dev/vda rw\",\"image\":\"smartxworks/virtink-kernel-5.15.12\"},\"memory\":{\"size\":\"1Gi\"}},\"networks\":[{\"name\":\"pod\",\"pod\":{}}],\"volumes\":[{\"containerRootfs\":{\"image\":\"smartxworks/virtink-container-rootfs-ubuntu\",\"size\":\"4Gi\"},\"name\":\"ubuntu\"},{\"cloudInit\":{\"userData\":\"#cloud-config\\npassword: password\\nchpasswd: { expire: False }\\nssh_pwauth: True\"},\"name\":\"cloud-init\"}]}}\n"
		},
		"managedFields": [{
			"manager": "kubectl-client-side-apply",
			"operation": "Update",
			"apiVersion": "virt.virtink.smartx.com/v1alpha1",
			"time": "2024-04-20T06:04:41Z",
			"fieldsType": "FieldsV1",
			"fieldsV1": {
				"f:metadata": {
					"f:annotations": {
						".": {},
						"f:kubectl.kubernetes.io/last-applied-configuration": {}
					}
				},
				"f:spec": {
					".": {},
					"f:instance": {
						".": {},
						"f:disks": {},
						"f:interfaces": {},
						"f:kernel": {
							".": {},
							"f:cmdline": {},
							"f:image": {}
						},
						"f:memory": {
							".": {},
							"f:size": {}
						}
					},
					"f:networks": {},
					"f:volumes": {}
				}
			}
		}, {
			"manager": "virt-controller",
			"operation": "Update",
			"apiVersion": "virt.virtink.smartx.com/v1alpha1",
			"time": "2024-04-20T06:04:41Z",
			"fieldsType": "FieldsV1",
			"fieldsV1": {
				"f:status": {
					"f:phase": {},
					"f:vmPodName": {}
				}
			},
			"subresource": "status"
		}, {
			"manager": "virt-daemon",
			"operation": "Update",
			"apiVersion": "virt.virtink.smartx.com/v1alpha1",
			"time": "2024-04-20T06:04:41Z",
			"fieldsType": "FieldsV1",
			"fieldsV1": {
				"f:status": {}
			},
			"subresource": "status"
		}]
	},
	"spec": {
		"resources": {},
		"runPolicy": "Once",
		"instance": {
			"cpu": {
				"sockets": 2,
				"coresPerSocket": 2
			},
			"memory": {
				"size": "8Gi"
			},
			"kernel": {
				"image": "smartxworks/virtink-kernel-5.15.12",
				"cmdline": "console=ttyS0 root=/dev/vda rw"
			},
			"disks": [{
				"name": "ubuntu"
			}, {
				"name": "cloud-init"
			}],
			"interfaces": [{
				"name": "pod",
				"mac": "52:54:00:e2:16:ea",
				"bridge": {}
			}]
		},
		"volumes": [{
			"name": "ubuntu",
			"containerRootfs": {
				"image": "smartxworks/virtink-container-rootfs-ubuntu",
				"size": "40Gi"
			}
		}, {
			"name": "cloud-init",
			"cloudInit": {
				"userData": "#cloud-config\npassword: password\nchpasswd: { expire: False }\nssh_pwauth: True"
			}
		}],
		"networks": [{
			"name": "pod",
			"pod": {}
		}]
	},
	"status": {
		"phase": "Scheduling",
		"vmPodName": "vm-ubuntu-container-rootfs-qgrdx"
	}
}
```

Guest OS version details:  ubuntu2204
Host OS version details: ubuntu2204
**Logs**
```bash
[root@master ~]# kubectl -n ns-jx00000003 logs pod/jx00000003-ops-81 
Defaulted container "cloud-hypervisor" out of: cloud-hypervisor, init-kernel (init), init-volume-ubuntu (init), init-volume-cloud-init (init)
2024/05/02 03:23:57 Failed to build VM config: setup bridge network: create bridge: file exists

```
