### ISSUE TITLE
Boot failure along side Kata on Raspberry Pi on Talos Linux

### ISSUE THREAD

**Issue by BobyMCbobs** [cloud-hypervisor/cloud-hypervisor#6524]
**Describe the bug**

The error occurs when starting a Pod using the kata-containers runtime which uses cloud-hypervisor.
```
ApiError(VmBoot(DeviceManager(CreateInterruptController(CreateGic(CreateVgic(Vgic error CreateGic(CreateDevice(No such device (os error 19))))))))): unknown
```

**To Reproduce**

1. write https://factory.talos.dev/image/0462506a8dde91a1f75ff4ae60dc74cedd1a96ea18742e4825b099eb67cdcd34/v1.7.4/metal-arm64.raw.xz to an SD card (or USB if USB booting is enabled). See here for [image factory page](https://factory.talos.dev/?arch=arm64&board=rpi_generic&cmdline-set=true&extensions=-&extensions=siderolabs%2Fkata-containers&platform=metal&target=sbc&version=1.7.4)
2. boot RPi
3. make some config with `talosctl gen config kata-test-cluster https://SOME_LOCAL_IP:6443`
4. apply the config with `talosctl apply-config --talosconfig ./talosconfig -n SOME_LOCAL_IP -e SOME_LOCAL_IP -i -f ./controlplane.yaml`
5. bootstrap with `talosctl bootstrap --talosconfig ./talosconfig -n SOME_LOCAL_IP -e SOME_LOCAL_IP`
6. get the kubeconfig `talosctl kubeconfig --talosconfig ./talosconfig -n SOME_LOCAL_IP -e SOME_LOCAL_IP`
7. install the RuntimeClass for Kata
```
kubectl apply -f- <<EOF
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
handler: kata
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
EOF
```
8. create a Pod
```
kubectl apply -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginx-kata
spec:
  runtimeClassName: kata
  containers:
  - name: nginx
    image: nginx
EOF
```
9. observe error with `kubectl describe pod nginx-data`, looking in Events

see more info here:
- https://www.talos.dev/v1.7/talos-guides/install/single-board-computers/rpi_generic/
- https://www.talos.dev/v1.7/introduction/prodnotes/#customizing-machine-configuration

**Version**

Output of `podman run --platform linux/arm64 -it --rm ghcr.io/siderolabs/kata-containers:3.3.0 /rootfs/usr/local/bin/cloud-hypervisor --version`: cloud-hypervisor v36.0.0

Did you build from source, if so build command line (e.g. features): https://github.com/siderolabs/extensions/blob/main/container-runtime/kata-containers/pkg.yaml#L38

---
related: https://github.com/siderolabs/extensions/issues/404
explore the built extension: https://oci.dag.dev/?image=ghcr.io/siderolabs/kata-containers@sha256:624962f2b6719e9599f66a1d8ad3dd0ca8c758d551e9c1f7b2cf59b8ebf35bf4&mt=application%2Fvnd.docker.distribution.manifest.v2%2Bjson&size=1087
